apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-service
  template:
    metadata:
      labels:
        app: ping-service
    spec:
      containers:
      - name: ping-service
        image: 242201311297.dkr.ecr.us-east-1.amazonaws.com/microservice-one:latest  # <-- CI will replace :latest with unique tag
        imagePullPolicy: IfNotPresent  # safer with immutable tags
        ports:
        - containerPort: 8002
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /ping
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ping
            port: 8002
          initialDelaySeconds: 10
          periodSeconds: 5

