apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-service
  template:
    metadata:
      labels:
        app: metrics-service
    spec:
      containers:
      - name: metrics-service
        image: 242201311297.dkr.ecr.us-east-1.amazonaws.com/microservice-two  # Replace with your image
        ports:
        - containerPort: 8001  # Replace with your actual port
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        
