apiVersion: apps/v1
kind: Deployment
metadata:
  name: metric-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metric-service
  template:
    metadata:
      labels:
        app: metric-service
    spec:
      containers:
      - name: metric-service
        image: 242201311297.dkr.ecr.us-east-1.amazonaws.com/microservice-two:8e09ed14-20250911-150943
        imagePullPolicy: IfNotPresent  # safe for immutable tags
        ports:
        - containerPort: 8001
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /metric
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /metric
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 5
