apiVersion: apps/v1
kind: Deployment
metadata:
  name: metric-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metric-service
  template:
    metadata:
      labels:
        app: metric-service
    spec:
      containers:
      - name: metric-service
        image: 242201311297.dkr.ecr.us-east-1.amazonaws.com/microservice-two:4acffc54-20250911-153754
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        # Liveness: checks full /metric endpoint
        livenessProbe:
          httpGet:
            path: /metric
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 5
        # Readiness: lightweight check on root
        readinessProbe:
          httpGet:
            path: /
            port: 8001
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
