apiVersion: v1
kind: Service
metadata:
  name: metrics-service
  namespace: microservices
spec:
  selector:
    app: metrics-service
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
  type: ClusterIP
