replicaCount: 1

ping_svc:
  enabled: true
  name: ping-service
  image:
    repository: 242201311297.dkr.ecr.us-east-1.amazonaws.com/microservice-one
    tag: "latest"
  containerPort: 8002
  servicePort: 8002

metric_svc:
  enabled: true
  name: metrics-service
  image:
    repository: 242201311297.dkr.ecr.us-east-1.amazonaws.com/microservice-two
    tag: "latest"
  containerPort: 8001
  servicePort: 8001

ingress:
  enabled: true
  name: microservices-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
  paths:
    - path: /ping
      serviceName: {{ .Values.ping_svc.name }}
      servicePort: {{ .Values.ping_svc.servicePort }}
    - path: /metrics
      serviceName: {{ .Values.metric_svc.name }}
      servicePort: {{ .Values.metric_svc.servicePort }}
