apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Prathameshsatyarthi123/helm_deployment'
    targetRevision: main
    path: ingress
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true