name: CI - Build & Push Images

on:
  push:
    branches:
      - main
    paths:
      - "ping_svc/**"
      - "metric_svc/**"
      - "**/deployment.yaml"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::242201311297:role/GitHubActionsECRRole
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Build & Push Ping Service
      - name: Build & Push ping_svc
        run: |
          IMAGE_URI=242201311297.dkr.ecr.us-east-1.amazonaws.com/microservice-one
          IMAGE_TAG=${GITHUB_SHA}
          docker build -t $IMAGE_URI:$IMAGE_TAG -f ./ping_svc/Dockerfile.ping ./ping_svc
          docker push $IMAGE_URI:$IMAGE_TAG
          echo "PING_IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      # Build & Push Metric Service
      - name: Build & Push metric_svc
        run: |
          IMAGE_URI=242201311297.dkr.ecr.us-east-1.amazonaws.com/microservice-two
          IMAGE_TAG=${GITHUB_SHA}
          docker build -t $IMAGE_URI:$IMAGE_TAG -f ./metric_svc/Dockerfile.metrics ./metric_svc
          docker push $IMAGE_URI:$IMAGE_TAG
          echo "METRIC_IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      # Update Deployment.yaml files with new image tags
      - name: Update Deployment manifests
        run: |
          find . -name deployment.yaml -exec sed -i "s|microservice-one:.*|microservice-one:${PING_IMAGE_TAG}|g" {} \;
          find . -name deployment.yaml -exec sed -i "s|microservice-two:.*|microservice-two:${METRIC_IMAGE_TAG}|g" {} \;

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add .
          git commit -m "Update image tags: ping=${PING_IMAGE_TAG}, metric=${METRIC_IMAGE_TAG}" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin main

