jobs:
  update-gitops:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CI repo (helm_deployment)
        uses: actions/checkout@v4

      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: Prathameshsatyarthi123/helm_deployment-gitops
          token: ${{ secrets.GITOPS_PAT }}   # 🔑 uses your PAT
          path: gitops   # this will clone into ./gitops folder

      - name: Update image tag in values.yaml
        run: |
          cd gitops/dev
          yq -i '.ping_svc.image.tag = "${{ github.run_number }}"' values.yaml
          yq -i '.metric_svc.image.tag = "${{ github.run_number }}"' values.yaml

      - name: Commit and push changes
        run: |
          cd gitops
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update image tags to ${{ github.run_number }}"
          git push origin main
