name: CI - Build & Push Images
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::242201311297:role/GitHubActionsECRRole
          aws-region: us-east-1
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      # Get short commit SHA for tagging
      - name: Get commit SHA
        id: commit
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
      # Build & Push Ping Service
      - name: Build & Push ping_svc
        run: |
          IMAGE_URI=242201311297.dkr.ecr.us-east-1.amazonaws.com/microservice-one
          docker build -t $IMAGE_URI:${{ steps.commit.outputs.sha }} -f ./ping_svc/Dockerfile.ping ./ping_svc
          docker push $IMAGE_URI:${{ steps.commit.outputs.sha }}
      
      # Build & Push Metric Service
      - name: Build & Push metric_svc
        run: |
          IMAGE_URI=242201311297.dkr.ecr.us-east-1.amazonaws.com/microservice-two
          docker build -t $IMAGE_URI:${{ steps.commit.outputs.sha }} -f ./metric_svc/Dockerfile.metrics ./metric_svc
          docker push $IMAGE_URI:${{ steps.commit.outputs.sha }}
      
      - name: Update deployment manifests
        run: |
          NEW_TAG="${{ steps.commit.outputs.sha }}"
          
          # Update ping service - flexible spacing pattern
          sed -i "s|image: 242201311297\.dkr\.ecr\.us-east-1\.amazonaws\.com/microservice-one:.*|image: 242201311297.dkr.ecr.us-east-1.amazonaws.com/microservice-one:${NEW_TAG}|g" ./ping_svc/deployment.yaml
          
          # Update metric service - flexible spacing pattern
          sed -i "s|image: 242201311297\.dkr\.ecr\.us-east-1\.amazonaws\.com/microservice-two:.*|image: 242201311297.dkr.ecr.us-east-1.amazonaws.com/microservice-two:${NEW_TAG}|g" ./metric_svc/deployment.yaml
          
          # Alternative approach using more specific pattern
          sed -i "s|\(.*image: 242201311297\.dkr\.ecr\.us-east-1\.amazonaws\.com/microservice-one:\).*|\1${NEW_TAG}|g" ./ping_svc/deployment.yaml
          sed -i "s|\(.*image: 242201311297\.dkr\.ecr\.us-east-1\.amazonaws\.com/microservice-two:\).*|\1${NEW_TAG}|g" ./metric_svc/deployment.yaml
          
          # Verify changes
          echo "=== After Update ==="
          echo "Ping service:"
          grep -n "image:" ./ping_svc/deployment.yaml || echo "No image line found in ping service"
          echo "Metric service:"
          grep -n "image:" ./metric_svc/deployment.yaml || echo "No image line found in metric service"
      
      # Commit changes so ArgoCD picks it up
      - name: Commit changes
        run: |
          git add .
          git commit -m "Update image tags to ${{ steps.commit.outputs.sha }}" || echo "No changes to commit"
          git push
